### ISSUE TITLE
Need to support nextjs 9.x

### ISSUE THREAD

**Issue by binsee** [hebertcisco/nestjs-undici#7]
Hi, I'm having the following problem trying to use this npm package.

```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-project@0.0.34
npm ERR! Found: @nestjs/common@9.1.6
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^9.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/common@"^7.0.0 || ^8.0.0" from nestjs-undici@0.0.4
npm ERR! node_modules/nestjs-undici
npm ERR!   nestjs-undici@"^0.0.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/binsee/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/binsee/.npm/_logs/2022-11-05T09_30_31_885Z-debug-0.log
```

I can submit a PR to fix it if needed.

**Comment by hebertcisco** [comment]
Now we support `nestjs 9.x`, your change has been accepted and merged, you will be able to verify that the workflow was successful, installing the dependencies correctly... Thanks for contributing!

Link: [Example workflow where the new version was run](https://github.com/hebertcisco/nestjs-techniques-undici/actions/runs/3400606006/jobs/5655146054)

**Comment by binsee** [comment]
> Now we support `nestjs 9.x`, your change has been accepted and merged, you will be able to verify that the workflow was successful, installing the dependencies correctly... Thanks for contributing!
> 
> Link: [Example workflow where the new version was run](https://github.com/hebertcisco/nestjs-techniques-undici/actions/runs/3400606006/jobs/5655146054)

Yes, it can be installed normally. cheers
